Add "order nulls last" global and per column options
jbox-web/ajax-datatables-rails pull request #279
Opened 2018-02-20 03:02 UTC by natebird

* Allows for nulls to be ordered last using a global configuration option using `config.nulls_last = true` in the `ajax_datatables_rails.rb` file.
* Allows for nulls to be ordered last on individual columns by adding `nulls_last: true` to the view_columns method in the datatable class.

2018-02-20 03:05 UTC, natebird commented
`active_record_filter_records_spec.rb:265` is failing on the master branch for me without any changes. The changes in this PR shouldn't have any effect on that test.

2018-03-21 13:04 UTC, natebird commented
Any update on getting this merged?

2018-05-01 21:57 UTC, ikaul commented
Will this be merged to the master branch any time soon?
I was looking forward to add this to my project.

2018-05-01 21:58 UTC, n-rodriguez commented
Well... I'd love to, but it seems it breaks tests for Rails prior to 5.x

2018-05-01 22:03 UTC, ikaul commented
Ah! Bummer.

2018-05-01 23:04 UTC, natebird commented
It's failing the Oracle tests after merging in some fixes from the master branch. @n-rodriguez any ideas on what is causing Oracle to fail? It looks like its just a missing dependency or something.

2018-05-01 23:07 UTC, n-rodriguez commented
Yeah it's normal. Oracle tests depends on my own login and password to download the archive.
The credentials are injected via environment variables but only on the master branch and on the main repo for security reasons.

2018-05-01 23:07 UTC, n-rodriguez commented
https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

2018-05-01 23:09 UTC, n-rodriguez requested changes

2018-05-01 23:09 UTC, n-rodriguez commented on spec/support/test_helpers.rb
> +
Maybe we can remove it? ;)

2018-05-01 23:09 UTC, n-rodriguez commented on spec/ajax-datatables-rails/datatable/column_spec.rb
> +      datatable.params[:columns] = {'0'=>{'data'=>'username', 'name'=>'', 'searchable'=>'true', 'orderable'=>'true', 'search'=>{'value'=>'searchvalue', 'regex'=>'false'}, 'nulls_last'=>'true'}}
I don't know if we really need this since it shoud be set in the Datatable class.

2018-05-01 23:18 UTC, natebird commented on spec/ajax-datatables-rails/datatable/column_spec.rb
> +      datatable.params[:columns] = {'0'=>{'data'=>'username', 'name'=>'', 'searchable'=>'true', 'orderable'=>'true', 'search'=>{'value'=>'searchvalue', 'regex'=>'false'}, 'nulls_last'=>'true'}}
It is being used. I think that is simulating setting it on the global variable. It's been a while since I've looked at this code.

2018-05-01 23:19 UTC, natebird commented on spec/ajax-datatables-rails/datatable/column_spec.rb
> +      datatable.params[:columns] = {'0'=>{'data'=>'username', 'name'=>'', 'searchable'=>'true', 'orderable'=>'true', 'search'=>{'value'=>'searchvalue', 'regex'=>'false'}, 'nulls_last'=>'true'}}
Removing that fails the test…

2018-05-05 07:02 UTC, n-rodriguez approved these changes

2018-05-05 07:03 UTC, merged

2018-05-05 07:03 UTC, n-rodriguez commented
Thank you!

2018-05-09 22:15 UTC, ikaul commented
Awesome, Thank you guys for working on this and getting this merged. This will help me make my datatables more presentable.