Improve query performance when nulls_last option is enabled
jbox-web/ajax-datatables-rails pull request #317
Opened 2019-01-17 19:57 UTC by natebird

The separate syntax per database driver allows indices to give performance improvements.

2019-01-17 20:04 UTC, aantillon commented on spec/ajax-datatables-rails/datatable/simple_order_spec.rb
> +      # end
please remove this lines if not needed

2019-01-17 20:05 UTC, aantillon requested changes
Awesome!

2019-01-17 20:06 UTC, natebird commented on spec/ajax-datatables-rails/datatable/simple_order_spec.rb
> +      # end
Good catch. Thanks. I pushed a fix.

2019-01-17 20:09 UTC, antillas21 approved these changes

2019-01-17 22:27 UTC, natebird commented
The ENV variable for the database adapter seems to be interfering with the tests I created. Any ideas on how to work around that?

2019-03-06 21:41 UTC, natebird commented
@antillas21 - can you review this again? It looks like a couple of failed tests due to not finding bundler. Anything you want me to do or is this ready to be merged?

2019-03-06 23:33 UTC, n-rodriguez commented on lib/ajax-datatables-rails/datatable/simple_order.rb
> +        when -> (a) { a.in?([:pg, :postgresql, :postgres, :oracle]) }
Why not :

```ruby
case AjaxDatatablesRails.config.db_adapter
when :pg, :postgresql, :postgres, :oracle
when :mysql, :mysql2, :sqlite, :sqlite3
end
```

2019-03-07 19:20 UTC, natebird commented on lib/ajax-datatables-rails/datatable/simple_order.rb
> +        when -> (a) { a.in?([:pg, :postgresql, :postgres, :oracle]) }
I'm not sure why I did it that way. I updated the case statement. Much better. Thanks!

2019-03-21 21:09 UTC, natebird commented
@n-rodriguez Can you look this over again? The Travis failures are related to not finding bundler.

2019-04-17 23:09 UTC, merged